a1 = float(input("enter the value of a1 : "))
a2 = float(input("enter the value of a2 : "))
a3= float(input("enter the value of a3 : "))
b1 = float(input("enter the value of b1 : "))
b2 = float(input("enter the value of b2 : "))
b3 = float(input("enter the value of b3 : "))

dp = (a1*b1 + a2*b2 + a3*b3)
print ("dot product of two vector is : ",dp)
print("thank you")
